#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================
ynh_script_progression "Loading installation settings..."

version=$(grep STD_VERSION $install_dir/boot.php |  cut -c 38- | rev | cut -c 5- | rev)
last_update=$(grep  update_time: /etc/yunohost/apps/$app/settings.yml |  cut -c 14-)

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

# Download, check integrity, uncompress and patch the source from app.src
# ynh_setup_source --dest_dir="$install_dir"

if [ `cd $install_dir && git rev-parse --is-inside-work-tree` ]; then
	pushd "$install_dir"
		git pull --quiet
		cd extend/addon/zaddons
		git pull --quiet
		cd ../../..
		filelist=(`ls extend/addon/zaddons`)
		cd addon
		for a in "${filelist[@]}" ; do
			base=`basename $a`
			if [ $base = '.git' ]; then
				#echo 'ignoring git'
				continue;
			fi
			if [ ! -d ../extend/addon/zaddons/$base ]; then
				#echo $a 'not a directory'
				continue;
			fi
			if [ -x $base ]; then
				#echo $base 'file exists'
				continue;
			fi

			echo linking $base

			ln -s ../extend/addon/zaddons/$base $base
		done
		for x in `ls` ; do
			if [ -L "$x" ] && ! [ -e "$x" ]; then
				echo "removing dead symlink $x" ;
				rm -- "$x";
			fi;
		done
	popd
	chmod -R 775 $install_dir/store
else

    # Create a temporary directory
	  tmpdir="$(ynh_smart_mktemp 6000)"
	# Backup the config file in the temp dir
	  cp -a "$install_dir/.htconfig.php" "$tmpdir/.htconfig.php"
 	  cp -a "$install_dir/store" "$tmpdir/store"
	  cp -a "$install_dir/php.log" "$tmpdir/php.log"
	  cp -a "$install_dir/cache" "$tmpdir/cache"

	# Remove the app directory securely
	ynh_safe_rm "$install_dir"

	# Download, check integrity, uncompress and patch the source from app.src
	ynh_setup_source --dest_dir="$install_dir"

	cp -a "$tmpdir/cache" "${install_dir}"
	cp -a "$tmpdir/store" "${install_dir}"
	cp -a "$tmpdir/.htconfig.php" "${install_dir}"
	cp -a "$tmpdir/php.log" "${install_dir}"
	ynh_safe_rm "$tmpdir"
	chmod -R 775 $install_dir/store
	mkdir $install_dir/addon
	ynh_setup_source --dest_dir="$install_dir/addon" --source_id="app_addons"
fi

#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod 750 "$install_dir"
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod -R o-rwx "$install_dir"
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R $app:www-data "$install_dir"
#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Upgrading NGINX web server configuration..."

# Create a dedicated nginx config
ynh_config_add_nginx

# Create a dedicated php-fpm config
ynh_config_add_phpfpm

# Use logrotate to manage app-specific logfile(s)
ynh_config_add_logrotate

ynh_config_add --template="poller-cron" --destination="/etc/cron.d/$app"
#REMOVEME? Assuming the file is setup using ynh_config_add, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown root: "/etc/cron.d/$app"
#REMOVEME? Assuming the file is setup using ynh_config_add, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod 644 "/etc/cron.d/$app"

ynh_config_add_fail2ban --logpath="$install_dir/php.log" --failregex="^.*auth\.php.*failed login attempt.*from IP <HOST>.*$"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
